#!/usr/bin/env php
<?php

use App\Console\ConsoleAppBootstrap;
use Wandu\Foundation\Application;

if (!file_exists(__DIR__ . '/vendor/autoload.php')) {
    echo "cannot find autoload.php. you may run composer install.\n";
    exit(-1);
}

$autoload = require_once __DIR__ . '/vendor/autoload.php';

$app = new Application(new ConsoleAppBootstrap());
$app->setAsGlobal();
exit($app->execute());
