<?php
namespace Wandu\Api\Error;

use Psr\Http\Message\ServerRequestInterface;
use Wandu\Foundation\Error\DefaultHttpErrorHandler;

class HttpErrorHandler extends DefaultHttpErrorHandler 
{
    public function handle(ServerRequestInterface $request, $exception)
    {
        return parent::handle($request, $exception); // TODO: Change the autogenerated stub
    }
}
